name: Build & Deploy

on:
  push:
    branches:
      - prod

jobs:
  # Make better testing later...
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Prepare for testing
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Install Codecov
        run: npm install -g codecov

      - name: Run Tests & Report Coverage
        run: npm run test:cov && codecov

      - name: Test building
        run: npm run build

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: test 

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPO_API }}

      - name: Redeploy on Server
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          body: '{"token": "${{ secrets.DEPLOY_TOKEN }}"}'
