name: Test & deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Prepare for testing
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Start Tests
        run: npm test

      - name: Test building
        run: npm run build

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [ test ]
    env:
      REPO: ${{ secrets.DOCKER_REPO_API }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build . -t $REPO
      - name: Push Docker image
        run: docker push $REPO
  
  deploy:
    name: Redeploy On Vps
    runs-on: ubuntu-18.04
    needs: [docker]
    steps:
       - name: Webhook Deploy
         uses: joelwmale/webhook-action@master
         env:
           WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
           data: '{"token": "${{ secrets.DEPLOY_TOKEN }}"}'
