name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint --if-present
    - run: npm run build --if-present
    - run: npm test
  
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO_API }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
      - needs: [build]
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build . -t $REPO
      - name: Push Docker image
        run: docker push $REPO
  
  deploy:
    name: Redeploy On Vps
    runs-on: ubuntu-18.04
    needs: [docker]
    steps:
       - name: Webhook Deploy
         uses: joelwmale/webhook-action@master
         env:
           WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
           data: '{"token": "${{ secrets.DEPLOY_TOKEN }}"}'